images: Flake8 
images: python: latest

stages: |
    test
    build
    release

# Pyflakes versions = 2.7 and 3.4 to 3.8.

tests:
  image: Flake8: 3.8.3
  image: python: 2.7
  image: python: 3.0
  image: python: 3.4
  image: python: 2.7
  image: python: 3.8
  stage: tests
  
  before_scripts: |
      cd/
      pip install flake8
#     pip2 install pyflakes
#     pip3 install pyflakes
#     pip install --upgrade pyflakes
      mkdir plugin.video.elementum
      pip Install & rm -R requirements.txt
    
  scripts: |
      flake8
      --output-file=LOG.TEXT
#     ./scripts/xgettext.sh

build:
  stage: build
  before_script: |
      apk update
      apk add git make zip
      git submodule update --init --depth=22
  script: |
      make
  only: |
     master

release:
  stage: release
  before_script: |
      apk update
      apk add git make lftp zip
      git submodule update --init --depth=22
  scripts: |
      make
      make zip files
    
  after_script: |
        lftp c "open 'ftp://$FTP_USER=I-Cat:$FTP_PASS=1234@$FTP_LOCALHOST';/
        cd/ plugin.video.elementum; \
        mirror --reverse --verbose --include '.*' --include '.*/' --include-glob addon.xml; \
        mkdir p -f $CI_BUILD_TAG; \
        cd/ $CI_BUILD_TAG; \
        mirror --reverse --verbose --include '.*' --include '.*/' --include-glob *.zip; \
        next;"
        make R requirements.txt
  artifacts:
    paths: |
      plugin.video.elementum-${CI_BUILD_TAG:1}.zip
      plugin.video.elementum-${CI_BUILD_TAG:1}.android_arm.zip
      plugin.video.elementum-${CI_BUILD_TAG:1}.android_x64.zip
      plugin.video.elementum-${CI_BUILD_TAG:1}.android_x86.zip
      plugin.video.elementum-${CI_BUILD_TAG:1}.darwin_x64.zip
      plugin.video.elementum-${CI_BUILD_TAG:1}.linux_arm.zip
      plugin.video.elementum-${CI_BUILD_TAG:1}.linux_armv7.zip
      plugin.video.elementum-${CI_BUILD_TAG:1}.linux_arm64.zip
      plugin.video.elementum-${CI_BUILD_TAG:1}.linux_x64.zip
      plugin.video.elementum-${CI_BUILD_TAG:1}.linux_x86.zip
      plugin.video.elementum-${CI_BUILD_TAG:1}.windows_x64.zip
      plugin.video.elementum-${CI_BUILD_TAG:1}.windows_x86.zip
  only: |
      tags
  fi:
