# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        
dist: bionic
language: python
python: 3.8

matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - env: REPO=repo-plugins BRANCH=gotham
    - env: REPO=repo-plugins BRANCH=helix
    - env: REPO=repo-plugins BRANCH=isengard
    - env: REPO=repo-plugins BRANCH=jarvis
    - env: REPO=repo-plugins BRANCH=krypton
    - env: REPO=repo-plugins BRANCH=leia
    - env: REPO=repo-plugins BRANCH=matrix
    - env: REPO=repo-scrapers BRANCH=gotham
    - env: REPO=repo-scrapers BRANCH=helix
    - env: REPO=repo-scrapers BRANCH=isengard
    - env: REPO=repo-scrapers BRANCH=jarvis
    - env: REPO=repo-scrapers BRANCH=krypton
    - env: REPO=repo-scrapers BRANCH=leia
    - env: REPO=repo-scrapers BRANCH=matrix
    - env: REPO=repo-resources BRANCH=isengard
    - env: REPO=repo-resources BRANCH=jarvis
    - env: REPO=repo-resources BRANCH=krypton
    - env: REPO=repo-resources BRANCH=leia
    - env: REPO=repo-resources BRANCH=matrix
    - env: REPO=repo-scripts BRANCH=gotham
    - env: REPO=repo-scripts BRANCH=helix
    - env: REPO=repo-scripts BRANCH=isengard
    - env: REPO=repo-scripts BRANCH=jarvis
    - env: REPO=repo-scripts BRANCH=krypton
    - env: REPO=repo-scripts BRANCH=leia
    - env: REPO=repo-scripts BRANCH=matrix
    - env: REPO=repo-skins BRANCH=krypton
    - env: REPO=repo-skins BRANCH=leia
    - env: REPO=repo-skins BRANCH=matrix
  allow_failures:
    - env: REPO=repo-plugins BRANCH=gotham
    - env: REPO=repo-plugins BRANCH=helix
    - env: REPO=repo-plugins BRANCH=isengard
    - env: REPO=repo-plugins BRANCH=jarvis
    - env: REPO=repo-plugins BRANCH=krypton
    - env: REPO=repo-plugins BRANCH=leia
    - env: REPO=repo-plugins BRANCH=matrix
    - env: REPO=repo-scrapers BRANCH=gotham
    - env: REPO=repo-scrapers BRANCH=helix
    - env: REPO=repo-scrapers BRANCH=isengard
    - env: REPO=repo-scrapers BRANCH=jarvis
    - env: REPO=repo-scrapers BRANCH=krypton
    - env: REPO=repo-scrapers BRANCH=leia
    - env: REPO=repo-scrapers BRANCH=matrix
    - env: REPO=repo-resources BRANCH=isengard
    - env: REPO=repo-resources BRANCH=jarvis
    - env: REPO=repo-resources BRANCH=krypton
    - env: REPO=repo-resources BRANCH=leia
    - env: REPO=repo-resources BRANCH=matrix
    - env: REPO=repo-scripts BRANCH=gotham
    - env: REPO=repo-scripts BRANCH=helix
    - env: REPO=repo-scripts BRANCH=isengard
    - env: REPO=repo-scripts BRANCH=jarvis
    - env: REPO=repo-scripts BRANCH=krypton
    - env: REPO=repo-scripts BRANCH=leia
    - env: REPO=repo-scripts BRANCH=matrix
    - env: REPO=repo-skins BRANCH=krypton
    - env: REPO=repo-skins BRANCH=leia
    - env: REPO=repo-skins BRANCH=matrix

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pylint

before_script:
  - if [[ -n "$REPO" && -n "$BRANCH" ]]; then
    git clone --branch=$BRANCH --depth=1 --single-branch https://github.com/xbmc/$REPO.git ../repo;
    fi

# command to run tests
script:
  - if [[ -n "$REPO" && -n "$BRANCH" ]]; then
    python3 -m kodi_addon_checker --branch=$BRANCH ../repo;
    fi
  - if [[ -z "$REPO" || -z "$BRANCH" ]]; then
    py.test -v;
    fi
  - if [[ -z "$REPO" || -z "$BRANCH" ]]; then
    pylint *;
    fi
    
 Run: addon-check: .travis.yml
 Build Config
{
  "language": "python",
  "os": [
    "linux"
  ],
  "dist": "bionic",
  "python": [
    "3.8"
  ],
  "install": [
    "pip install -r requirements.txt",
    "pip install pylint"
  ],
  "before_script": [
    "if [[ -n \"$REPO\" && -n \"$BRANCH\" ]]; then git clone --branch=$BRANCH --depth=1 --single-branch https://github.com/xbmc/$REPO.git ../repo; fi"
  ],
  "script": [
    "if [[ -n \"$REPO\" && -n \"$BRANCH\" ]]; then python3 -m kodi_addon_checker --branch=$BRANCH ../repo; fi",
    "if [[ -z \"$REPO\" || -z \"$BRANCH\" ]]; then py.test -v; fi",
    "if [[ -z \"$REPO\" || -z \"$BRANCH\" ]]; then pylint *; fi"
  ],
  "jobs": {
    "include": [
      {
        "python": "3.5"
      },
      {
        "python": "3.6"
      },
      {
        "python": "3.7"
      },
      {
        "python": "3.8"
      },
      {
        "env": [
          {
            "REPO": "repo-plugins",
            "BRANCH": "gotham"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-plugins",
            "BRANCH": "helix"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-plugins",
            "BRANCH": "isengard"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-plugins",
            "BRANCH": "jarvis"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-plugins",
            "BRANCH": "krypton"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-plugins",
            "BRANCH": "leia"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-plugins",
            "BRANCH": "matrix"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-scrapers",
            "BRANCH": "gotham"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-scrapers",
            "BRANCH": "helix"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-scrapers",
            "BRANCH": "isengard"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-scrapers",
            "BRANCH": "jarvis"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-scrapers",
            "BRANCH": "krypton"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-scrapers",
            "BRANCH": "leia"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-scrapers",
            "BRANCH": "matrix"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-resources",
            "BRANCH": "isengard"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-resources",
            "BRANCH": "jarvis"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-resources",
            "BRANCH": "krypton"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-resources",
            "BRANCH": "leia"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-resources",
            "BRANCH": "matrix"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-scripts",
            "BRANCH": "gotham"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-scripts",
            "BRANCH": "helix"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-scripts",
            "BRANCH": "isengard"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-scripts",
            "BRANCH": "jarvis"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-scripts",
            "BRANCH": "krypton"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-scripts",
            "BRANCH": "leia"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-scripts",
            "BRANCH": "matrix"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-skins",
            "BRANCH": "krypton"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-skins",
            "BRANCH": "leia"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-skins",
            "BRANCH": "matrix"
          }
        ]
      }
    ],
    "allow_failures": [
      {
        "env": [
          {
            "REPO": "repo-plugins",
            "BRANCH": "gotham"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-plugins",
            "BRANCH": "helix"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-plugins",
            "BRANCH": "isengard"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-plugins",
            "BRANCH": "jarvis"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-plugins",
            "BRANCH": "krypton"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-plugins",
            "BRANCH": "leia"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-plugins",
            "BRANCH": "matrix"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-scrapers",
            "BRANCH": "gotham"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-scrapers",
            "BRANCH": "helix"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-scrapers",
            "BRANCH": "isengard"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-scrapers",
            "BRANCH": "jarvis"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-scrapers",
            "BRANCH": "krypton"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-scrapers",
            "BRANCH": "leia"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-scrapers",
            "BRANCH": "matrix"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-resources",
            "BRANCH": "isengard"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-resources",
            "BRANCH": "jarvis"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-resources",
            "BRANCH": "krypton"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-resources",
            "BRANCH": "leia"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-resources",
            "BRANCH": "matrix"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-scripts",
            "BRANCH": "gotham"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-scripts",
            "BRANCH": "helix"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-scripts",
            "BRANCH": "isengard"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-scripts",
            "BRANCH": "jarvis"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-scripts",
            "BRANCH": "krypton"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-scripts",
            "BRANCH": "leia"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-scripts",
            "BRANCH": "matrix"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-skins",
            "BRANCH": "krypton"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-skins",
            "BRANCH": "leia"
          }
        ]
      },
      {
        "env": [
          {
            "REPO": "repo-skins",
            "BRANCH": "matrix"
          }
        ]
      }
    ]
  }
}
